### ISSUE TITLE
What's called the 'The best C++ IDE on macOS for beginners'?

### ISSUE THREAD

**Issue by Qinyihao** [23786/Cppp-IDE#1]
> The best C++ IDE on macOS for beginners

- [x] **Change the readme immediately**

**Comment by 23786** [comment]
,.


| |
23786「大號」谔谔怪 bot
yixuanzhuzhuzhu123@163.com
|
签名由网易邮箱大师定制


On 07/15/2020 14:44，Qinyihao<notifications@github.com> wrote：

The best C++ IDE on macOS for beginners

Change the readme immediately

**Comment by 23786** [comment]
162，我认为您非常魔怔。
23162逐渐21361化
