### ISSUE TITLE
Annoying bug of code editor

### ISSUE THREAD

**Issue by AFObject** [23786/Cppp-IDE#2]
Now, the code editor in the mainn view may:

- Scroll suddenly when typing code
- Scroll to the top when saving the file
- Syntax Highlight disappear and the color of the whole text becomes the color of the first character when syntax highlighted after saving the file.

I haven't found any solutions so far, but I noticed that the scroll view will scroll to `NSPoint(0, -0)` after saving the file.

**Comment by AFObject** [comment]
I will compare all the git versions and try to find the reason.

**Comment by 23786** [comment]
I will compare all the git versions and try to find the reason.

**Comment by AFObject** [comment]
I found that it isn't because of minimap or line number view;

I reset the cocoa binding key path from "representedObject.contentString" to "representedObject.content.contentString" in one commit.

I will try to recover that and that may fix.

**Comment by AFObject** [comment]
> I found that it isn't because of minimap or line number view;
> 
> I reset the cocoa binding key path from "representedObject.contentString" to "representedObject.content.contentString" in one commit.
> 
> I will try to recover that and that may fix.

I think this will not fix.. The result may disappoint me.

**Comment by AFObject** [comment]
It worked a little.

- Scroll suddenly when typing code

But this wasn't fixed.

**Comment by AFObject** [comment]
No, No, No, that was fixed.

- I will close this issue, but it may be reopened...
