### ISSUE TITLE
Please make a built .app file of this app

### ISSUE THREAD

**Issue by qinyihao** [23786/Cppp-IDE#6]
<img width="1440" alt="Screen Shot 2021-02-27 at 12 15 49" src="https://user-images.githubusercontent.com/40647091/109375165-88a88c00-78f5-11eb-98af-95e9112d87d2.png">

Xcode just keep downloading all kinds of things.

**Comment by AFObject** [comment]
> <img alt="Screen Shot 2021-02-27 at 12 15 49" width="1440" src="https://user-images.githubusercontent.com/40647091/109375165-88a88c00-78f5-11eb-98af-95e9112d87d2.png">
> 
> Xcode just keep downloading all kinds of things.

Sorry, version 3.0 development hasn't ended yet. 

因为开学了所以要咕咕咕  咕到暑假都有可能

**Comment by AFObject** [comment]
@qinyihao

**Comment by AFObject** [comment]
如果您真的要 Build 的话：

- 把 Swift Package 都删掉
- 把 SwiftLSPClient 库删掉，现在不需要它了
- 把 C+++/Classes/Server/CDServer.swift 暂时注释掉

**Comment by qinyihao** [comment]
啊这

还有，您这个apple id在build的时候会失败（

**Comment by qinyihao** [comment]
还有您有很多东西没有上传到github上面，导致xcodeproj找不到文件build失败

**Comment by swiftqwq** [comment]
> 还有您有很多东西没有上传到github上面，导致xcodeproj找不到文件build失败

如果都上传的话`clone`会需要很长时间吧。。。。
